// ─── Fundamentals accessor ────────────────────────────────────────────────────
// Merges the two sources into the shape thesis pages consume:
//
//   reported.json  — SEC XBRL, generated by scripts/fetchFundamentals.ts.
//                    Automated, auditable, refreshed on demand.
//   manual.ts      — everything free automation can't reach reliably.
//
// Reported data wins where it exists. Manual fills gaps and supplies metrics
// that were never in XBRL to begin with.

import reportedRaw from "./reported.json";
import { MANUAL_SERIES, manualValuation } from "./manual";
import type { MetricSeries, MetricUnit, DataPoint } from "../thesis/types";

interface RawQuarter {
  period: string;
  periodEnd: string;
  value: number;
  derived?: boolean;
}

interface RawTicker {
  ticker: string;
  cik: string;
  metrics: Record<string, RawQuarter[]>;
  conceptUsed: Record<string, string>;
  latestPeriodEnd?: string;
  fetchedAt: string;
}

const reported = reportedRaw as unknown as Record<string, RawTicker>;

/** Display metadata per SEC metric key. */
const METRIC_META: Record<string, { label: string; unit: MetricUnit; scale: number }> = {
  revenue:           { label: "Revenue",              unit: "usd_b", scale: 1e9 },
  premiumsEarned:    { label: "Premiums earned, net", unit: "usd_b", scale: 1e9 },
  grossProfit:       { label: "Gross profit",         unit: "usd_b", scale: 1e9 },
  operatingIncome:   { label: "Operating income",     unit: "usd_b", scale: 1e9 },
  netIncome:         { label: "Net income",           unit: "usd_b", scale: 1e9 },
  operatingCashFlow: { label: "Operating cash flow",  unit: "usd_b", scale: 1e9 },
  epsDiluted:        { label: "Diluted EPS",          unit: "x",     scale: 1 },
};

/** "2026-06-30" → "Q2 2026", for freshness stamps. */
function quarterLabel(periodEnd: string): string {
  const [y, m] = periodEnd.split("-").map(Number);
  return `Q${Math.floor((m - 1) / 3) + 1} ${y}`;
}

export function dataThroughLabel(ticker: string): string | undefined {
  const end = reported[ticker.toUpperCase()]?.latestPeriodEnd;
  return end ? `Financial data through ${quarterLabel(end)}` : undefined;
}

/** One SEC-derived metric as a chart-ready series. */
export function reportedSeries(
  ticker: string,
  metric: string,
  opts: { quarters?: number; label?: string } = {}
): MetricSeries | undefined {
  const rec = reported[ticker.toUpperCase()];
  const raw = rec?.metrics?.[metric];
  if (!raw || raw.length === 0) return undefined;

  const meta = METRIC_META[metric];
  if (!meta) return undefined;

  const slice = raw.slice(-(opts.quarters ?? 8));
  const points: DataPoint[] = slice.map((q) => ({
    period: q.period,
    value: q.value / meta.scale,
  }));

  const anyDerived = slice.some((q) => q.derived);

  return {
    label: opts.label ?? meta.label,
    unit: meta.unit,
    points,
    source: "sec",
    dataThrough: `Financial data through ${quarterLabel(
      slice[slice.length - 1].periodEnd
    )}`,
    note:
      (rec.conceptUsed[metric] ? `SEC XBRL: ${rec.conceptUsed[metric]}. ` : "") +
      (anyDerived
        ? "Q4 derived as the fiscal-year total less the other three quarters, since XBRL has no standalone Q4 duration."
        : ""),
  };
}

/** Margin series (%) computed from two reported dollar metrics. */
export function marginSeries(
  ticker: string,
  numerator: string,
  denominator: string,
  label: string,
  quarters = 8
): MetricSeries | undefined {
  const rec = reported[ticker.toUpperCase()];
  const num = rec?.metrics?.[numerator];
  const den = rec?.metrics?.[denominator];
  if (!num || !den) return undefined;

  const denByEnd = new Map(den.map((d) => [d.periodEnd, d.value]));
  const points: DataPoint[] = [];
  for (const n of num.slice(-quarters)) {
    const d = denByEnd.get(n.periodEnd);
    if (d === undefined || d === 0) continue;
    points.push({ period: n.period, value: (n.value / d) * 100 });
  }
  if (points.length < 2) return undefined;

  const lastEnd = num[num.length - 1].periodEnd;
  return {
    label,
    unit: "pct",
    points,
    source: "sec",
    dataThrough: `Financial data through ${quarterLabel(lastEnd)}`,
    note: `Computed from SEC-reported ${numerator} ÷ ${denominator}.`,
  };
}

/** Year-over-year growth (%) for a reported metric. */
export function yoyGrowthSeries(
  ticker: string,
  metric: string,
  label: string
): MetricSeries | undefined {
  const rec = reported[ticker.toUpperCase()];
  const raw = rec?.metrics?.[metric];
  if (!raw || raw.length < 5) return undefined;

  const points: DataPoint[] = [];
  for (let i = 4; i < raw.length; i++) {
    const prior = raw[i - 4].value;
    if (!prior) continue;
    points.push({
      period: raw[i].period,
      value: ((raw[i].value - prior) / Math.abs(prior)) * 100,
    });
  }
  if (points.length === 0) return undefined;

  return {
    label,
    unit: "pct",
    points: points.slice(-8),
    source: "sec",
    dataThrough: `Financial data through ${quarterLabel(
      raw[raw.length - 1].periodEnd
    )}`,
    note: "Year-over-year change, same quarter prior year, from SEC-reported figures.",
  };
}

/** Hand-maintained series for a ticker. */
export function manualSeries(ticker: string): MetricSeries[] {
  return MANUAL_SERIES[ticker.toUpperCase()] ?? [];
}

export { manualValuation };

/** Whether any reported financials exist — false for ETFs and NBIS. */
export function hasReportedFinancials(ticker: string): boolean {
  const rec = reported[ticker.toUpperCase()];
  return Boolean(rec && Object.keys(rec.metrics).length > 0);
}

/** Which SEC concept supplied a metric, for the source line on the page. */
export function conceptFor(ticker: string, metric: string): string | undefined {
  return reported[ticker.toUpperCase()]?.conceptUsed?.[metric];
}

export const automatedTickers = Object.keys(reported);
