// ─── Decision history ─────────────────────────────────────────────────────────
// The Decision Log is HISTORY. It is never the source of current holdings —
// data/portfolioState.ts owns that. Replaying this log to derive today's book
// would let one missing entry silently corrupt the live portfolio.
//
// Organised by company: one block per ticker, decisions chronological inside it.
// The old single reverse-chronological feed made it impossible to read one
// position's arc without scrolling past everything else.
//
// ── WEIGHTS ARE PENDING, NOT ESTIMATED ──────────────────────────────────────
// Every event carries optional oldWeightPct / newWeightPct. The repository does
// not contain the transaction-level history and dated portfolio values needed to
// compute real "% of book" transitions, so they are left undefined and render as
// "pending" rather than being back-filled with plausible numbers. The schema is
// ready for the Robinhood transaction history.
//
// ── GROUPING RULES ──────────────────────────────────────────────────────────
//   Same ticker, same day        → one event (merged automatically below).
//   Same thesis, multiple days   → one event via a shared `groupId`; the event
//                                  spans first date → last date, and the weight
//                                  transition runs from before the first trade
//                                  to after the final one.

import { decisionLog, type DecisionEntry } from "./decisionLog";
import { companies, getCompany, type HoldingStatus } from "./companies";
import computedWeights from "./decisionWeights.json";
import lifecycle from "./lifecycleEvents.json";

export type DecisionAction = "Add" | "Trim" | "Exit" | "Rebalance" | "Initiate" | "Re-enter";

/** A weight that may legitimately not be known yet. */
export type PendingWeight = number | undefined;

export interface DecisionEvent {
  /** First trade date in this event, "YYYY-MM-DD" or "YYYY-MM". */
  startDate: string;
  /** Last trade date, when the event spans several days. */
  endDate?: string;
  action: DecisionAction;
  /** Raw action label from source when it doesn't map cleanly. */
  actionLabel: string;
  /** % of book before the first trade. Undefined = pending. */
  oldWeightPct: PendingWeight;
  /** % of book after the final trade. Undefined = pending. */
  newWeightPct: PendingWeight;
  rationale: string;
  /** Groups multi-day trades driven by one thesis into a single event. */
  groupId?: string;
  /** True when dated to a month snapshot because no exact date survives. */
  dateApproximate?: boolean;
  /** False when `rationale` is a template fallback rather than something
   *  actually written about this decision. Drives whether the UI renders it
   *  as prose or as a small "no contemporaneous rationale" tag. */
  hasRealRationale: boolean;
  /** How the weights were derived, when they were. */
  weightBasis?: "reconstructed-daily-close";
  /** Valuation close used for oldWeightPct — provenance shown on hover. */
  priorCloseDate?: string;
  /** Valuation close used for newWeightPct. */
  endCloseDate?: string;
  /** Why a weight could not be reconstructed. */
  weightPendingReason?: string;
}

export interface CompanyDecisions {
  ticker: string;
  company: string;
  status: HoldingStatus | "unknown";
  /** Status label as shown on the block header. */
  statusLabel: string;
  events: DecisionEvent[];
  /** Whether any event in this block still needs real weight data. */
  hasPendingWeights: boolean;
}

// ── Computed weights ─────────────────────────────────────────────────────────
// data/decisionWeights.json is generated by scripts/computeDecisionWeights.ts
// from the private ledger. It is committed because it holds only tickers, dates
// and percentages — the reconstruction inputs (prices, share counts, dollar
// values) never leave the local pipeline.
//
// Denominator is SECURITIES-ONLY, matching the Investments page, so residual
// cash bookkeeping cannot shift a displayed security weight.

interface ComputedWeight {
  ticker: string;
  startDate: string;
  endDate?: string;
  oldWeightPct?: number;
  newWeightPct?: number;
  priorCloseDate?: string;
  endCloseDate?: string;
  status: "computed" | "pending";
  pendingReason?: string;
}

const COMPUTED = new Map<string, ComputedWeight>(
  (computedWeights.events as ComputedWeight[]).map((e) => [
    `${e.ticker}|${e.startDate}|${e.endDate ?? ""}`,
    e,
  ])
);

function computedFor(
  ticker: string,
  startDate: string,
  endDate?: string
): ComputedWeight | undefined {
  return COMPUTED.get(`${ticker}|${startDate}|${endDate ?? ""}`);
}

// ── Lifecycle events (Initiate / Re-enter) ───────────────────────────────────
// data/lifecycleEvents.json is derived from the transaction ledger and supplies
// the zero-crossings the hand-written log omitted. Without them a company block
// could open mid-story, e.g. "3.70% -> 4.39%" for a position that had already
// been held for months.
//
// Rationale: the six positions opened in the Aug 2026 rebalance carry the
// reasoning already established for them. Everything else gets factual wording,
// because inventing a contemporaneous rationale for a years-old transaction
// would be fabrication.

interface LifecycleRow {
  ticker: string;
  action: "Initiate" | "Re-enter";
  startDate: string;
  endDate?: string;
  intervalIndex: number;
}

const INITIATION_RATIONALE: Record<string, string> = {
  AMZN: "Opened on weakness. The position is held for AWS: cloud and compute demand should keep compounding, and AWS is one of the largest high-quality infrastructure businesses in the world. Amazon's ecommerce and logistics scale sit underneath that, with robotics as optionality rather than a reason to own it.",
  SGOV: "Opened as the portfolio's cash allocation. Keeps capital liquid and earning while waiting for better entry points, and can be redeployed when individual holdings or the broader market create them.",
  GLDM: "Opened as ballast against a growth-heavy book. The market is still working through AI capital spending, monetization expectations, macro conditions and geopolitical risk, and gold responds to a different set of factors than the rest of the portfolio.",
  CEG: "Opened on weakness as the preferred way to hold the nuclear thesis. More established than the speculative alternatives, with a fleet already operating rather than awaiting permitting.",
  MA: "Opened to move exposure away from the AI and compute theme. The attraction is network economics, margins, and the ability to compound alongside rising payment volume without taking bank-style credit risk.",
  CBRS: "Opened as a direct expression of the view that agentic AI increases inference demand. Deliberately small: the company is early and competes against an entrenched accelerator ecosystem.",
};

const FACTUAL_INITIATION =
  "Position initiated. Transaction history establishes the allocation change; a separate contemporaneous rationale was not archived.";
const FACTUAL_REENTRY =
  "Position re-entered after a full exit. Transaction history establishes the allocation change; a separate contemporaneous rationale was not archived.";

// ── Boilerplate detection ────────────────────────────────────────────────────
// The hand-written log (data/decisionLog.ts) predates the company registry and
// carries a handful of template fallbacks of its own, written when a real,
// dated rationale for that specific decision was not on record. Matched by
// their stable anchor phrase rather than full-string equality, since the
// surrounding sentence names a different ticker or theme each time.
const BOILERPLATE_PATTERNS: RegExp[] = [
  /^Position initiated\. Transaction history establishes the allocation change/,
  /^Position re-entered after a full exit\. Transaction history establishes the allocation change/,
  /^Closed position\. No further rationale recorded in source/,
  /^Currently held\. Specific buy-decision dates for this position are not captured/,
  /Exact trim date not preserved in source records/,
  /, extending the .+ allocation within the account\.$/,
];

/** True when `text` is a template fallback, not something written about this decision. */
function isBoilerplateRationale(text: string | undefined): boolean {
  if (!text) return true;
  return BOILERPLATE_PATTERNS.some((re) => re.test(text));
}

// ── Guard: a Trim or Add requires evidence of an actual transaction ─────────
// A weight decrease between two tracker snapshots can come from dilution
// (capital added to other positions) or price depreciation, not a sale. A
// weight increase can come from other holdings' prices falling or an
// unrelated allocation shift, not a purchase. Treating a snapshot-to-snapshot
// weight delta alone as evidence of a Trim or Add produced five phantom
// events (Aug 2026: META, GOOGL, NBIS, UNH tagged "Trim"; RKLB, MELI, FBTC
// tagged "Add"), none of which could be confirmed against transaction
// records and all of which were removed from data/decisionLog.ts.
//
// The note text alone cannot be the check: a real, confirmed trade with an
// unknown exact day (VOO's July trim) reads identically to a purely inferred
// one. So this requires a positive, human-asserted flag instead of pattern-
// matching the prose. Fails the build if a month-resolution Trim or Add is
// missing it.
function assertNoUnevidencedTransactionEvents(log: DecisionEntry[]): void {
  const offenders = log.filter(
    (e) =>
      e.date.length === 7 &&
      (e.action === "Trim" || e.action === "Add") &&
      !e.dateApproximateButConfirmed
  );
  if (offenders.length > 0) {
    const list = offenders.map((e) => `${e.ticker} (${e.date})`).join(", ");
    throw new Error(
      `data/decisionLog.ts has a month-resolution Trim or Add event without ` +
        `dateApproximateButConfirmed set: ${list}. A weight change between two ` +
        `tracker snapshots is not evidence of a trade on its own. Confirm the ` +
        `transaction actually happened (e.g. against real transaction history) ` +
        `and set dateApproximateButConfirmed: true, or remove the event.`
    );
  }
}

assertNoUnevidencedTransactionEvents(decisionLog);

function lifecycleEventsFor(ticker: string): DecisionEvent[] {
  return (lifecycle.events as LifecycleRow[])
    .filter((e) => e.ticker === ticker)
    .map((e) => {
      const rationale =
        e.action === "Initiate"
          ? (INITIATION_RATIONALE[ticker] ?? FACTUAL_INITIATION)
          : FACTUAL_REENTRY;
      return {
        startDate: e.startDate,
        endDate: e.endDate,
        action: e.action === "Initiate" ? ("Initiate" as const) : ("Re-enter" as const),
        actionLabel: e.action,
        oldWeightPct: undefined,
        newWeightPct: undefined,
        rationale,
        hasRealRationale: !isBoilerplateRationale(rationale),
        groupId: `lifecycle-${ticker}-${e.intervalIndex}`,
      };
    });
}

// ── Normalisation ────────────────────────────────────────────────────────────

const ACTION_MAP: Record<string, DecisionAction> = {
  Add: "Add",
  Buy: "Add",
  Initiate: "Initiate",
  Trim: "Trim",
  Exit: "Exit",
  Rebalance: "Rebalance",
};

function normaliseAction(raw: string): DecisionAction {
  return ACTION_MAP[raw] ?? "Rebalance";
}

/** "12.5%" → 12.5. Returns undefined for anything unparseable. */
function parseWeight(raw: string | undefined): PendingWeight {
  if (!raw) return undefined;
  const n = Number.parseFloat(raw.replace("%", "").trim());
  return Number.isFinite(n) ? n : undefined;
}

function statusLabelFor(
  registryStatus: HoldingStatus | undefined,
  sourceStatus: DecisionEntry["status"]
): string {
  if (registryStatus === "active") {
    return sourceStatus === "Partially Trimmed" ? "Held · partially trimmed" : "Held";
  }
  if (registryStatus === "exited") return "Exited";
  // Ticker predates the company registry — fall back to what the log recorded.
  if (sourceStatus === "Held") return "Held";
  if (sourceStatus === "Partially Trimmed") return "Held · partially trimmed";
  if (sourceStatus === "Fully Exited") return "Exited";
  return "Status not recorded";
}

/**
 * Merge events that represent one decision.
 *
 * Same-day trades in the same ticker collapse automatically. Multi-day runs
 * collapse when they share a groupId. In both cases the merged event spans the
 * earliest start to the latest end, and the weight transition is taken from the
 * first event's opening weight to the last event's closing weight — so once real
 * weights land, a combined event reads "before the first trade → after the last".
 */
function mergeEvents(events: DecisionEvent[], ticker: string): DecisionEvent[] {
  const buckets = new Map<string, DecisionEvent[]>();
  for (const e of events) {
    // groupId wins; otherwise same action on the same date is one decision.
    const key = e.groupId ?? `${e.startDate}|${e.action}`;
    const list = buckets.get(key);
    if (list) list.push(e);
    else buckets.set(key, [e]);
  }

  const merged: DecisionEvent[] = [];
  for (const group of buckets.values()) {
    if (group.length === 1) {
      merged.push(group[0]);
      continue;
    }
    const sorted = [...group].sort((a, b) => a.startDate.localeCompare(b.startDate));
    const first = sorted[0];
    const last = sorted[sorted.length - 1];
    const endDate = last.endDate ?? last.startDate;

    merged.push({
      ...first,
      endDate: endDate === first.startDate ? undefined : endDate,
      oldWeightPct: first.oldWeightPct,
      newWeightPct: last.newWeightPct,
      // Keep every distinct rationale; identical text isn't repeated.
      rationale: [...new Set(sorted.map((e) => e.rationale).filter(Boolean))].join(" "),
      // A merged event counts as "real" if any of the trades it absorbed did,
      // even when a boilerplate fallback from another trade rides along.
      hasRealRationale: sorted.some((e) => e.hasRealRationale),
      dateApproximate: sorted.some((e) => e.dateApproximate),
    });
  }

  // Overlay reconstructed weights onto the merged events. Anything the
  // reconstruction could not pin stays undefined and renders as pending.
  for (const e of merged) {
    const c = computedFor(ticker, e.startDate, e.endDate);
    if (c?.status === "computed") {
      e.oldWeightPct = c.oldWeightPct;
      e.newWeightPct = c.newWeightPct;
      e.weightBasis = "reconstructed-daily-close";
      e.priorCloseDate = c.priorCloseDate;
      e.endCloseDate = c.endCloseDate;
    } else if (c?.pendingReason) {
      e.weightPendingReason = c.pendingReason;
    }
  }

  return merged.sort((a, b) => a.startDate.localeCompare(b.startDate));
}

function toEvent(entry: DecisionEntry): DecisionEvent {
  return {
    startDate: entry.date,
    action: normaliseAction(entry.action),
    actionLabel: entry.decisionAction ?? entry.action,
    // Real weights only. The legacy log carries a couple of string weights on
    // ad-hoc entries; anything else stays undefined and renders as pending.
    oldWeightPct: parseWeight(entry.oldWeight),
    newWeightPct: parseWeight(entry.newWeight),
    rationale: entry.note,
    hasRealRationale: !isBoilerplateRationale(entry.note),
    groupId: entry.groupId,
    dateApproximate: entry.date.length === 7,
  };
}

// ── Public accessor ──────────────────────────────────────────────────────────

/**
 * All decision history, grouped by company. Active holdings first (heaviest
 * weight leads), then exited names, then tickers that predate the registry.
 * Nothing is dropped because a position was closed.
 */
export function decisionsByCompany(): CompanyDecisions[] {
  const byTicker = new Map<string, DecisionEntry[]>();
  for (const entry of decisionLog) {
    const list = byTicker.get(entry.ticker);
    if (list) list.push(entry);
    else byTicker.set(entry.ticker, [entry]);
  }
  // A ticker can have real, dated lifecycle events reconstructed from actual
  // transaction history with zero surviving hand-written rows, e.g. after an
  // inferred entry with no real evidence behind it is removed (see the
  // no-weight-delta-inference guard below). Seed those tickers too, or a
  // company with a perfectly real history would silently vanish from this
  // page for having no entry in the hand-written log.
  for (const row of lifecycle.events as LifecycleRow[]) {
    if (!byTicker.has(row.ticker)) byTicker.set(row.ticker, []);
  }

  const blocks: CompanyDecisions[] = [];
  for (const [ticker, entries] of byTicker) {
    const registry = getCompany(ticker);
    const lifecycleRows = lifecycleEventsFor(ticker);
    const lifecycleDates = new Set(lifecycleRows.map((e) => e.startDate));
    // Months covered by a dated zero-crossing. A hand-written row that only
    // recorded a month is the same decision the ledger now dates exactly, so it
    // defers rather than surviving as a second, permanently-pending event.
    const lifecycleMonths = new Set(lifecycleRows.map((e) => e.startDate.slice(0, 7)));
    const handWritten = entries
      .map(toEvent)
      // A hand-written row on the same date as a derived zero-crossing is the
      // same decision; the derived one wins because it carries the correct
      // Initiate/Re-enter action and a 0% opening weight.
      .filter((e) => !lifecycleDates.has(e.startDate))
      .filter((e) => !(e.startDate.length === 7 && lifecycleMonths.has(e.startDate)));
    const events = mergeEvents([...lifecycleRows, ...handWritten], ticker);
    // Nothing survived for this ticker at all (shouldn't happen given the
    // seeding above, but guards against a future refactor silently regressing it).
    if (events.length === 0) continue;

    blocks.push({
      ticker,
      company: registry?.name ?? entries[0]?.company ?? ticker,
      status: registry?.status ?? "unknown",
      statusLabel: statusLabelFor(registry?.status, entries[0]?.status),
      events,
      hasPendingWeights: events.some(
        (e) => e.oldWeightPct === undefined || e.newWeightPct === undefined
      ),
    });
  }

  const rank = (b: CompanyDecisions) =>
    b.status === "active" ? 0 : b.status === "exited" ? 1 : 2;

  return blocks.sort((a, b) => {
    const r = rank(a) - rank(b);
    if (r !== 0) return r;
    // Within a tier, most recent activity first.
    const aLast = a.events[a.events.length - 1]?.startDate ?? "";
    const bLast = b.events[b.events.length - 1]?.startDate ?? "";
    return bLast.localeCompare(aLast);
  });
}

/** Count of events still awaiting real weight data, for the pending banner. */
export function pendingWeightEventCount(): number {
  return decisionsByCompany().reduce(
    (n, b) =>
      n +
      b.events.filter(
        (e) => e.oldWeightPct === undefined || e.newWeightPct === undefined
      ).length,
    0
  );
}

/** Total events across every company, held or exited. */
export function totalEventCount(): number {
  return decisionsByCompany().reduce((n, b) => n + b.events.length, 0);
}

/** Count of events with an actual written rationale, not a template fallback. */
export function realRationaleEventCount(): number {
  return decisionsByCompany().reduce(
    (n, b) => n + b.events.filter((e) => e.hasRealRationale).length,
    0
  );
}

// ── Guard: Held/Exited status must derive from one rule ─────────────────────
// data/companies.ts hand-sets status: "active" | "exited" per ticker. That
// field is the practical source Investments and thesis navigation read, but
// it can drift silently from the decision history it is supposed to
// summarize — exactly what happened when VOO, CRWD, and FBTC were removed
// from the Aug 2026 holdings snapshot without a corresponding Exit event ever
// being added to data/decisionLog.ts. The registry said "exited"; the log
// said nothing happened. Both cannot be true.
//
// The rule, enforced here rather than just documented: a company is exited
// if and only if its most recent decision-log event (lifecycle events
// included) is an explicit Exit. This throws at module load, so a future
// registry/log mismatch fails the build instead of shipping quietly.
function assertStatusMatchesLastEvent(): void {
  const blocks = decisionsByCompany();
  const byTicker = new Map(blocks.map((b) => [b.ticker, b]));
  const mismatches: string[] = [];

  for (const c of companies) {
    const block = byTicker.get(c.ticker);
    const last = block?.events[block.events.length - 1];
    const lastIsExit = last?.action === "Exit";

    if (c.status === "exited" && !lastIsExit) {
      mismatches.push(
        `${c.ticker}: registry says "exited" but its most recent decision-log ` +
          `event is ${last ? `"${last.action}" (${last.startDate})` : "missing entirely"}, not an Exit.`
      );
    }
    if (c.status === "active" && lastIsExit) {
      mismatches.push(
        `${c.ticker}: registry says "active" but its most recent decision-log ` +
          `event is an Exit (${last!.startDate}).`
      );
    }
  }

  if (mismatches.length > 0) {
    throw new Error(
      `Held/Exited status mismatch between data/companies.ts and the decision log:\n` +
        mismatches.join("\n") +
        `\nEither the registry status is wrong, or the log is missing the event that ` +
        `actually justifies it. Do not fix this by guessing a date; find the real ` +
        `transaction and add it, or correct the registry.`
    );
  }
}

assertStatusMatchesLastEvent();
