// ─── Position lifecycle events ────────────────────────────────────────────────
//   npx tsx scripts/computeLifecycleEvents.ts
//
// Derives every ZERO CROSSING from the private ledger and writes
// data/lifecycleEvents.json (PUBLIC: ticker, dates, action only).
//
// WHY: the hand-written Decision Log recorded adds and trims but frequently
// omitted the transaction where a position first crossed 0% -> positive. A
// company block that opens with "3.70% -> 4.39%" implies the position appeared
// from nowhere. These events supply the missing Initiate / Re-enter rows so
// every block starts where the position actually started.
//
//   first interval        -> Initiate
//   any later interval    -> Re-enter  (a full exit happened in between)
//
// Multi-day opening builds driven by one decision are collapsed into a single
// event spanning first to last execution.

import { ingestLedger } from "../lib/reconstruction/ingest";
import { readFileSync, writeFileSync } from "node:fs";
import { reconstruct } from "../lib/reconstruction/engine";
import { asTradedClose, type PriceCache } from "../lib/reconstruction/prices";
import { ownershipIntervals } from "../lib/reconstruction/fifo";
import { isPubliclyExcluded } from "../lib/reconstruction/exclusions";

const INCEPTION = "2025-07-03";

/** Opening builds that span more than one session but express one decision. */
const OPENING_BUILD_END: Record<string, string> = {
  GLDM: "2026-08-11", // two fills across consecutive sessions
};


export interface LifecycleEvent {
  ticker: string;
  action: "Initiate" | "Re-enter";
  startDate: string;
  endDate?: string;
  /** Ordinal of the ownership interval this opens (0 = first ever). */
  intervalIndex: number;
}

function main() {
  const px = JSON.parse(readFileSync("data/priceCache.local.json", "utf8")) as PriceCache;
  const cal = px.tradingDays.filter((d) => d >= INCEPTION);
  const { transactions: txs, audit } = ingestLedger(px.tradingDays, INCEPTION);
  const res = reconstruct(txs, {
    from: INCEPTION, to: cal[cal.length - 1],
    opening: { date: INCEPTION, shares: {}, cash: 0 },
    calendar: cal, splits: px.splits,
    priceLookup: (t, d) => asTradedClose(t, d, px),
  });

  console.log(`source audit: rows=${audit.rowCount} owningAccountIds=${audit.owningAccountIds} foreignRows=${audit.foreignRows}`);
  const tickers = ([...new Set(txs.map((t) => t.ticker).filter(Boolean))] as string[])
    .filter((t) => !isPubliclyExcluded(t));
  const events: LifecycleEvent[] = [];
  for (const ticker of tickers.sort()) {
    ownershipIntervals(res.days, ticker).forEach((iv, i) => {
      const end = i === 0 ? OPENING_BUILD_END[ticker] : undefined;
      events.push({
        ticker,
        action: i === 0 ? "Initiate" : "Re-enter",
        startDate: iv.from,
        endDate: end && end !== iv.from ? end : undefined,
        intervalIndex: i,
      });
    });
  }

  writeFileSync("data/lifecycleEvents.json", JSON.stringify({
    _note:
      "Generated by scripts/computeLifecycleEvents.ts from the private ledger. " +
      "Tickers, dates and actions only. Supplies the Initiate / Re-enter events " +
      "the hand-written Decision Log omitted.",
    generatedAt: new Date().toISOString().slice(0, 10),
    inceptionDate: INCEPTION,
    events,
  }, null, 2) + "\n");

  const init = events.filter((e) => e.action === "Initiate").length;
  console.log(`events=${events.length}  initiations=${init}  re-entries=${events.length - init}`);
  for (const e of events.filter((e) => e.action === "Re-enter")) {
    console.log(`  RE-ENTER ${e.ticker.padEnd(6)} ${e.startDate}`);
  }
}

main();
